// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:505998269631:web:f4ef097be1aa1e8aa73a0a',
    messagingSenderId: '505998269631',
    projectId: 'project-9e980',
    authDomain: 'project-9e980.firebaseapp.com',
    storageBucket: 'project-9e980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:505998269631:android:5b3267592f1f20eba73a0a',
    messagingSenderId: '505998269631',
    projectId: 'project-9e980',
    storageBucket: 'project-9e980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:505998269631:ios:160820987a135172a73a0a',
    messagingSenderId: '505998269631',
    projectId: 'project-9e980',
    storageBucket: 'project-9e980.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:505998269631:ios:160820987a135172a73a0a',
    messagingSenderId: '505998269631',
    projectId: 'project-9e980',
    storageBucket: 'project-9e980.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:505998269631:web:127d36eb239d8dd0a73a0a',
    messagingSenderId: '505998269631',
    projectId: 'project-9e980',
    authDomain: 'project-9e980.firebaseapp.com',
    storageBucket: 'project-9e980.firebasestorage.app',
  );
}
